---
- name: base
  hosts: all
  roles:
  - role: base

- name: haproxy
  hosts: kubernetes_haproxy
  roles:
  - role: haproxy

- name:  kubernetes
  hosts: kubernetes_servers
  roles:
  - role: docker

  - role: kubernetes

  - role: metrics-server
