---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install epel
  yum:
    name: epel-release
    state: latest

- name: Install extras
  yum:
    name: 
      - "@Development Tools"
      - tmux
      - vim
      - htop
      - telnet
      - net-tools
      - tcpdump
      - jq
